data_path: dataset/raw/fraud_detection.csv
dataset_fraud_detection_cleaned_path: dataset/processed/fraud_detection_cleaned.pkl

# Debug related
print_debug: true

# column by data type related
float_columns: 
- amount

int_columns: 
- label

categorical_columns:
- merchant_type
- device_type

label: label

range_amount:
- 0
- 900

range_label:
- 0
- 1

train_set_path:
  - dataset/processed/X_train.pkl
  - dataset/processed/y_train.pkl

valid_set_path:
  - dataset/processed/X_valid.pkl
  - dataset/processed/y_valid.pkl

test_set_path:
  - dataset/processed/X_test.pkl
  - dataset/processed/y_test.pkl

train_processed_set_path:
  - dataset/processed/X_train_processed.pkl
  - dataset/processed/y_train_processed.pkl

train_processed_log_set_path:
  - dataset/processed/X_train_processed_log.pkl
  - dataset/processed/y_train_processed_log.pkl

train_processed_SMOTE_set_path:
  - dataset/processed/X_train_processed_SMOTE.pkl
  - dataset/processed/y_train_processed_SMOTE.pkl

train_processed_log_SMOTE_set_path:
  - dataset/processed/X_train_processed_log_SMOTE.pkl
  - dataset/processed/y_train_processed_log_SMOTE.pkl

valid_processed_set_path:
  - dataset/processed/X_valid_processed.pkl
  - dataset/processed/y_valid_processed.pkl

valid_processed_log_set_path:
  - dataset/processed/X_valid_processed_log.pkl
  - dataset/processed/y_valid_processed_log.pkl

test_processed_set_path:
  - dataset/processed/X_test_processed.pkl
  - dataset/processed/y_test_processed.pkl

test_processed_log_set_path:
  - dataset/processed/X_test_processed_log.pkl
  - dataset/processed/y_test_processed_log.pkl


features:
- amount 
- merchant_type_electronics 
- merchant_type_groceries
- merchant_type_others 
- merchant_type_travel 
- device_type_mobile
- device_type_tablet

features_log:
- merchant_type_electronics 
- merchant_type_groceries
- merchant_type_others 
- merchant_type_travel 
- device_type_mobile
- device_type_tablet
- log_amount